services:
  - type: web
    name: latex-compiler
    env: python
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y --no-install-recommends texlive-latex-base texlive-latex-extra texlive-fonts-recommended
      pip install -r requirements.txt
    startCommand: python app.py
